
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ushi
 */
public class Control extends javax.swing.JFrame {

    /**
     * Creates new form Control
     */
    
    static String conf_control = "";
    static int indice_1 = -1;
    static int indice_2 = -1;
    teclaso ventana = new teclaso();
    //Inicio bd = new Inicio();
//    static int tiempo = 0;
    
    public Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblderecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblizquierda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsalto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbldisparo = new javax.swing.JLabel();
        bvolver = new javax.swing.JButton();
        cbd1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbldisparos = new javax.swing.JLabel();
        cbd2 = new javax.swing.JComboBox<>();
        bdisp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Controles");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Derecha:");

        lblderecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblderecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblderechaMouseClicked(evt);
            }
        });

        jLabel3.setText("Izquierda:");

        lblizquierda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblizquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblizquierdaMouseClicked(evt);
            }
        });

        jLabel2.setText("Salto:");

        lblsalto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblsalto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsaltoMouseClicked(evt);
            }
        });

        jLabel4.setText("Disparo 1:");

        lbldisparo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbldisparo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldisparoMouseClicked(evt);
            }
        });

        bvolver.setText("Volver");
        bvolver.setFocusable(false);
        bvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvolverActionPerformed(evt);
            }
        });

        cbd1.setModel(new javax.swing.DefaultComboBoxModel(Inicio.disparos));
        cbd1.setFocusable(false);
        cbd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbd1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Disparo 2:");

        lbldisparos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbldisparos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldisparosMouseClicked(evt);
            }
        });

        cbd2.setModel(new javax.swing.DefaultComboBoxModel<>(Inicio.disparos));
        cbd2.setFocusable(false);

        bdisp.setText("Guardar");
        bdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdispActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bvolver)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbldisparos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldisparo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsalto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbd1, 0, 90, Short.MAX_VALUE)
                    .addComponent(cbd2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bdisp)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblsalto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lbldisparo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lbldisparos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(cbd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bdisp)
                        .addGap(56, 56, 56)))
                .addComponent(bvolver)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblderechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblderechaMouseClicked
        // TODO add your handling code here:
        conf_control = "derecha";
        ventana.setSize(300, 200);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
//        tiempo = Integer.parseInt(ventana.time);
        new Timer(5000,new Control.Timerventana()).start();
    }//GEN-LAST:event_lblderechaMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == ventana.keyderecha){
            System.out.println(key + " - " + ventana.keyderecha);
        }else if(key == ventana.keyizquierda){
            System.out.println(key + " - " + ventana.keyizquierda);
        }
    }//GEN-LAST:event_formKeyPressed

    private void lblizquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblizquierdaMouseClicked
        // TODO add your handling code here:
        conf_control = "izquierda";
        ventana.setSize(300, 200);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        new Timer(5000,new Control.Timerventana()).start();
    }//GEN-LAST:event_lblizquierdaMouseClicked

    private void bvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_bvolverActionPerformed

    private void lblsaltoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaltoMouseClicked
        // TODO add your handling code here:
        conf_control = "salto";
        ventana.setSize(300, 200);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        new Timer(5000,new Control.Timerventana()).start();
    }//GEN-LAST:event_lblsaltoMouseClicked

    private void cbd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbd1ActionPerformed

    private void lbldisparoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldisparoMouseClicked
        // TODO add your handling code here:
        conf_control = "disparo1";
        ventana.setSize(300, 200);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        new Timer(5000,new Control.Timerventana()).start();
    }//GEN-LAST:event_lbldisparoMouseClicked

    private void lbldisparosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldisparosMouseClicked
        // TODO add your handling code here:
        conf_control = "disparo2";
        ventana.setSize(300, 200);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        new Timer(5000,new Control.Timerventana()).start();
    }//GEN-LAST:event_lbldisparosMouseClicked

    private void bdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdispActionPerformed
        // TODO add your handling code here:
        indice_1 = cbd1.getSelectedIndex();
        indice_2 = cbd2.getSelectedIndex();
        //String selected_text = cbd1.getItemAt(cbd1.getSelectedIndex());
        System.out.println(indice_1 + " - " + indice_2);
    }//GEN-LAST:event_bdispActionPerformed

    private class Timerventana implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
//            tiempo--;
//            ventana.time = Integer.toString(tiempo);
            ventana.dispose();
            ((Timer) ae.getSource()).stop();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdisp;
    private javax.swing.JButton bvolver;
    private javax.swing.JComboBox<String> cbd1;
    private javax.swing.JComboBox<String> cbd2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblderecha;
    private javax.swing.JLabel lbldisparo;
    private javax.swing.JLabel lbldisparos;
    private javax.swing.JLabel lblizquierda;
    private javax.swing.JLabel lblsalto;
    // End of variables declaration//GEN-END:variables
}
